version: '3.9'

services:
  db:
    image: postgres:17
    restart: always
    container_name: bookstore-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: B2k25ismine@1$
      POSTGRES_DB: bookstore
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
